{{ config(materialized='incremental', on_schema_change='sync_all_columns', tags=['feature','main'],   unique_key=['race_id', 'kettonum'],) }}

with base as (
  select
    race_id,
    kettonum,
    horse_name,
    horse_number,
    gate_number,
    jockey_cd,
    jockey_cat,
    sire_id,
    sire_name,
    dam_id,
    damsire_id,
    sire_cat,
    breeder_cd,
    trainer_cd,
    age,
    h_weight,
    h_weight_bin,
    weight_change,
    dm_rank,
    sex_cd,
    kinryo,
    tozai_cd,
    popularity,
    odds_tansho,
    result_order,
    running_style_cd,
    agari3f,
    agari3f_rank_in_race,
    agari3f_rank_percentile_in_race,
    time_diff,
    is_win,
    track_cd,
    held_date,
    held_year_month,
    held_year,
    jyo_cd,
    distance_m,
    surface,
    surface_condition,
    surface_condition_cd,
    old_cd,
    race_level,
    num_starters,
    ten3f,
    ten4f,
    agari3f_race,
    agari4f_race,
    ten3f_ntile,
    course_cluster,
    turn_direction,
    turn_direction_cd,
    straight_distance_m,
    has_homestretch_slope,
    case
      when straight_distance_m is null then null
      when straight_distance_m < 300 then 1
      when straight_distance_m < 350 then 2
      when straight_distance_m < 400 then 3
      when straight_distance_m < 500 then 4
      else 5
    end as straight_distance_bucket,
    race_pace,
    wood_lap_time_1,
    wood_lap_time_2,
    wood_haron_time_4,
    wood_lap_time_1_z_tozai_day,
    wood_haron_time_4_z_tozai_day,
    wood_4f1f_profile_cat3,
    wood_tozai_cd,
    wood_late_sharpness,
    week1_wood_lap_time_1,
    week1_wood_lap_time_2,
    week1_wood_haron_time_4,
    week1_wood_lap_time_1_z_tozai_day,
    week1_wood_haron_time_4_z_tozai_day,
    week1_wood_tozai_cd,
    week1_wood_late_sharpness,
    hanro_lap_time_1,
    hanro_lap_time_2,
    hanro_haron_time_4,
    hanro_lap_time_1_z_tozai_day,
    hanro_haron_time_4_z_tozai_day,
    hanro_4f1f_profile_cat3,
    hanro_tozai_cd,
    hanro_late_sharpness,
    week1_hanro_lap_time_1,
    week1_hanro_lap_time_2,
    week1_hanro_haron_time_4,
    week1_hanro_lap_time_1_z_tozai_day,
    week1_hanro_haron_time_4_z_tozai_day,
    week1_hanro_tozai_cd,
    week1_hanro_late_sharpness,
    popularity_ratio,
    horse_number_ratio,
    sprint_decay,
    corner4_pos,
    held_month,
    age_month,
    age_days,
    pace_type,
    agari_good,
    ensei_type,
    kinryo_adj,
    is_place,
    blinker_cd
  from {{ ref('int_race_entry_enriched') }}
  {% if is_incremental() %}
    where held_date >= current_date - interval '7 days'
  {% endif %}
  
),

metrics as (
  select
    *
  from {{ ref('int_race_entry_metrics') }}
)

select
  b.race_id,
  b.kettonum,
  b.horse_name,
  b.horse_number,
  b.gate_number,
  b.jockey_cd,
  b.jockey_cat,
  b.sire_id,
  b.sire_name,
  b.dam_id,
  b.damsire_id,
  b.sire_cat,
  b.breeder_cd,
  b.trainer_cd,
  b.age,
  b.h_weight,
  b.h_weight_bin,
  b.weight_change,
  b.dm_rank,
  b.sex_cd,
  b.kinryo,
  b.tozai_cd,
  b.popularity,
  b.odds_tansho,
  b.result_order,
  b.running_style_cd,
  b.agari3f,
  b.agari3f_rank_in_race,
  b.agari3f_rank_percentile_in_race,
  b.time_diff,
  b.is_win,
  b.track_cd,
  b.held_date,
  b.held_year_month,
  b.held_year,
  b.jyo_cd,
  b.distance_m,
  b.surface,
  b.surface_condition,
  b.surface_condition_cd,
  b.old_cd,
  b.race_level,
  b.num_starters,
  b.ten3f,
  b.ten4f,
  b.agari3f_race,
  b.agari4f_race,
  b.ten3f_ntile,
  b.course_cluster,
  b.turn_direction,
  b.turn_direction_cd,
  b.straight_distance_m,
  b.has_homestretch_slope,
  b.straight_distance_bucket,
  b.race_pace,
  b.wood_lap_time_1,
  b.wood_lap_time_2,
  b.wood_haron_time_4,
  b.wood_lap_time_1_z_tozai_day,
  b.wood_haron_time_4_z_tozai_day,
  b.wood_4f1f_profile_cat3,
  b.wood_tozai_cd,
  b.wood_late_sharpness,
  b.week1_wood_lap_time_1,
  b.week1_wood_lap_time_2,
  b.week1_wood_haron_time_4,
  b.week1_wood_lap_time_1_z_tozai_day,
  b.week1_wood_haron_time_4_z_tozai_day,
  b.week1_wood_tozai_cd,
  b.week1_wood_late_sharpness,
  b.hanro_lap_time_1,
  b.hanro_lap_time_2,
  b.hanro_haron_time_4,
  b.hanro_lap_time_1_z_tozai_day,
  b.hanro_haron_time_4_z_tozai_day,
  b.hanro_4f1f_profile_cat3,
  b.hanro_tozai_cd,
  b.hanro_late_sharpness,
  b.week1_hanro_lap_time_1,
  b.week1_hanro_lap_time_2,
  b.week1_hanro_haron_time_4,
  b.week1_hanro_lap_time_1_z_tozai_day,
  b.week1_hanro_haron_time_4_z_tozai_day,
  b.week1_hanro_tozai_cd,
  b.week1_hanro_late_sharpness,
  b.popularity_ratio,
  b.horse_number_ratio,
  b.sprint_decay,
  b.corner4_pos,
  b.held_month,
  b.age_month,
  b.age_days,
  b.pace_type,
  b.agari_good,
  b.ensei_type,
  b.kinryo_adj,
  b.is_place,
  b.blinker_cd,
  m.time_vs_avg,
  m.time_vs_pace_avg,
  m.relative_agari3f,
  m.ten3f_vs_avg,
  m.ten3f_vs_avg_z,
  m.ten3f_avg_z,
  m.ten4f_vs_avg,
  m.ten4f_vs_avg_front_runners,
  m.time_diff_adjusted,
  m.pos4_agari_synergy,
  m.pos4_z,
  m.pace_front_disadvantage,
  m.pos4_agari_synergy_hensachi,
  m.jockey_starts_3y,
  m.jockey_avg_place_rate,
  m.jockey_avg_place_rate_smooth,
  m.jockey_place_rate_3y_logit,
  m.jockey_place_rate_3y_logit_smooth,
  m.jockey_place_rate_3y_smooth,
  m.jockey_avg_place_rate_corrected,
  m.jockey_avg_place_rate_corrected_smooth,
  m.jockey_cluster_avg_place_rate_corrected,
  m.jockey_cluster_avg_place_rate_corrected_smooth

from base b
left join metrics m
  on b.race_id = m.race_id
  and b.kettonum = m.kettonum
  {% if is_incremental() %}
    where held_date >= current_date - interval '7 days'
  {% endif %}
